#!/bin/bash
# /etc/init.d/docker-registry
# debian-compatible jenkins startup script.
# Mütze <muetze@scoutnet.de>
#
### BEGIN INIT INFO
# Provides:          docker-registry
# Required-Start:    $remote_fs $syslog $network
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start Docker Registry at boot time
# Description:       Controls Docker Registry
### END INIT INFO


case "$1" in
  start)
    docker run -d -p 5000:5000 --restart=always --name registry registry:2
    ;;
  stop)
    docker stop registry && docker rm -v registry
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
    exit 3
    ;;
esac

exit 0
